wolfSSL/wolfCLU

configure.ac

Same code that was used in wolfSSH

pull in existing code for --with-wolfssl and --prefix

---

.gitignore
src/clu_main.c
src/hash/clu_md5.c
src/tools/clu_funcs.c
src/x509/clu_request_setup.c

The initial changes to ultimately support a 140-3 + wolfCLU test.

Initial work on 140-3 + wolfCLU test

---

src/client/clu_client_setup.c

fix for buffer issue with s_client

---

src/clu_main.c
src/ecparam/clu_ecparam.c
src/genkey/clu_genkey.c
src/genkey/clu_genkey_setup.c
src/x509/clu_x509_sign.c
tests/pkey/ecparam-test.sh

better handling of curve name with key generation

---

src/x509/clu_cert_setup.c
tests/x509/x509-process-test.sh

Prior to this commit, x509 commands to convert between formats (or between the same format, e.g. PEM to PEM) would potentially alter the data in the certificate because of an intermediate transformation to a WOLFSSL_X509 object. For example, converting a PEM cert to PEM would internally create a WOLFSSL_X509 and then use that to generate the output. In some cases, the extensions in the output cert would be in a different order than the input, which is not ok because that invalidates the signature on the cert. This commit makes it so any encoding conversion doesn't modify the cert.

Improve x509 command.

---

src/dh/clu_dh.c

fixes for older versions of wolfSSL when checking the dh params

make dh param buffers dynamic

---

src/pkey/clu_rsa.c
tests/pkey/rsa-test.sh
tests/x509/x509-req-test.sh

-  Change der usage in clu_rsa.c in response to https://github.com/wolfSSL/wolfssl/pull/5257
-  Modify rsa and req unit tests and expected values corresponding to changes in https://github.com/wolfSSL/wolfssl/commit/0b78961111ea926f8ea918d12dd1222c8ecbfca5 and https://github.com/wolfSSL/wolfssl/commit/f479600066e4537d6b00d42e4db1d57125139d36

Maintain wolfCLU with wolfSSL master

---

src/tools/clu_funcs.c
src/x509/clu_config.c
src/x509/clu_request_setup.c
tests/x509/x509-req-test.sh
wolfclu/x509/clu_parse.h

Test case was added and now parsing a conf file that has both critical and lower case true for basic constraint.

fix for parsing basic constraint from conf file when critical or lower case

---

tests/x509/x509-process-test.sh

String for signature algo changed to signature value in more recent openssl versions.

fix for testing interop with newer openssl versions

---

configure.ac
src/x509/clu_request_setup.c

For when https://github.com/wolfSSL/wolfssl/pull/5213 is merged

check for wolfSSL_X509_REQ_print before compiling in local copy

---

README.md
wolfCLU.vcxproj

Brought to attention by zd#15262

VS build: Generate .exe for all platforms

---

src/tools/clu_funcs.c
src/x509/clu_cert_setup.c
tests/x509/x509-req-test.sh

Added -req, -signkey, -extfile, -extensions and -md options.
-req : require csr file
-singkey  : read sign key file
-extfile : read config file
-extensions : read extensions section in config file
-* :  Any supported digest for signing

Added some options for x509

---

README.md

Added an example in the README for creating a CA and signing other certs

README CA example

---

configure.ac
src/x509/clu_config.c
tests/dgst/dgst-test.sh
tests/pkey/ecparam-test.sh
tests/x509/x509-ca-test.sh
tests/x509/x509-process-test.sh
tests/x509/x509-req-test.sh

Fix for zd16305. Tests will fail until https://github.com/wolfSSL/wolfssl/pull/6525 is merged

Add ability to set more subjectAltName attributes

---

src/x509/clu_cert_setup.c

Account for behavior added in https://github.com/wolfSSL/wolfssl/pull/6891

Handle potential pointer increment in wolfSSL_i2d_X509

---

src/clu_main.c
src/genkey/clu_genkey.c
src/genkey/clu_genkey_setup.c
src/sign-verify/clu_sign.c
src/sign-verify/clu_sign_verify_setup.c
src/sign-verify/clu_verify.c
src/tools/clu_funcs.c
tests/genkey_sign_ver/genkey-sign-ver-test.sh
wolfclu/clu_optargs.h
wolfclu/genkey/clu_genkey.h
wolfclu/sign-verify/clu_sign.h
wolfclu/sign-verify/clu_verify.h

XMSS/XMSS^MT test program supports only XMSS-SHA2_10-256 because any other algorithms take too long time to test.

Support XMSS-XMSS^MT gnkey, sign and verify

---

certs/ca-int-cert.pem
certs/ca-int2-cert.pem
certs/client-int-cert.pem
certs/renew.sh
tests/x509/x509-verify-test.sh

Adds a test case for this change (https://github.com/wolfSSL/wolfCLU/pull/162)

add test case for partial chain verification

---

ChangeLog.md
configure.ac
src/sign-verify/clu_sign.c
src/sign-verify/clu_verify.c
tests/genkey_sign_ver/genkey-sign-ver-test.sh
wolfclu/version.h

Adds changlog and improved check for algo support with test case.

release version 0.1.7

---

src/tools/clu_funcs.c

Try old SN style to account for differences in OBJ_sn2nid

---

src/tools/clu_funcs.c

list -pubin in help menu with ecc verify
