wolfSSL/wolfCLU

- src/crypto/clu_evp_crypto.c
- src/tools/clu_funcs.c
- Change instances of `WOLFCLU_LOG(WOLFCLU_L0, "")` to `WOLFCLU_LOG(WOLFCLU_L0,
" ")` so that the compiler doesn't complain about 0-length format strings.
- In clu_funcs.c, I was getting warnings about the `XSTRNCPY` calls in
`wolfCLU_getAlgo`. It was warning that we weren't copying the null terminator.
I made the algo names const char arrays, and then we copy only up to the size
of the destination buffer. `strncpy` will 0-pad for us, so we don't need to
`memset` the destination buffer to 0s.
> Make a couple fixes for compilation errors/warnings.

- ChangeLog.md
- configure.ac
- src/clu_main.c
- src/sign-verify/clu_dgst_setup.c
- src/x509/clu_cert_setup.c
- src/x509/clu_parse.c
- wolfclu/version.h
Adds in a ChangeLog.md, fixes a few return items found during release testing and added in a wolfCrypt init/cleanup.
Also adds in a call to turn on wolfSSL debugging logs if wolfSSL has been compiled with debug enabled.
> Release version 0.0.6

- src/client/client.c
fixes use of s_client when wolfCLU is being ran from a directory other than the root directory, i.e
```
./configure && make && make install
mkdir tmp
cd tmp
wolfssl s_client -connect www.wolfssl.com:443
```
> fix for out of directory s_client use

- src/pkcs/clu_pkcs12.c
- src/pkey/clu_pkey.c
- adds support for -out with pkcs12
- PKCS12_parse in wolfSSL does not populate the WOLFSSL_EC_KEY in WOLFSSL_EVP_PKEY, this works around that for now and will also handle in the future if wolfSSL is updated to populate the structure.
> add -out for pkcs12 and handle ECC key

- src/tools/clu_funcs.c
- src/x509/clu_ca_setup.c
- src/x509/clu_cert_setup.c
- src/x509/clu_config.c
- src/x509/clu_parse.c
- src/x509/clu_request_setup.c
- src/x509/clu_x509_sign.c
- tests/x509/x509-process-test.sh
- wolfclu/clu_header_main.h
- wolfclu/x509/clu_parse.h
Adds support to the x509 command for:
- -subject
- -issuer
- -serial
- -dates
- -email
- -fingerprint
- -purpose
- -hash (note that wolfSSL_X509_NAME_hash does not match up with OpenSSL, needs investigating in wolfSSL library)
> expand x509 command

- src/x509/clu_request_setup.c
First if statement handles printing if `sz>(int)sizeof(byte)`  and the else if statement handles the `sz<=(int)sizeof(byte)` case. This rearrangement avoids having the `sz<=(int)sizeof(byte)` if statement inside of the if statement of `sz>1`, as the former would never be true if the latter one is.
> Print x509 serial edge case improvement

- src/client/client.c
- src/client/clu_client_setup.c
- wolfclu/clu_optargs.h
Tested locally using wolfSSL example certs. We should add a test script for s_client eventually, though.
> Add support for s_client flags -CAfile and -verify_return_error.

- src/x509/clu_request_setup.c
- tests/x509/x509-req-test.sh
this PR also fixes default basic constraint behavior, restricting it to only when generating self signed certificates without a basic constraint set
> fix up subject print expected for test with latest wolfSSL version

- configure.ac
- src/sign-verify/clu_crl_verify.c
- tests/x509/CRL-verify-test.sh
```
lealem@ubuntu:~/HOME/wolfCLU$ ./wolfssl crl -in crl.pem -text -noout
Certificate Revocation List (CRL):
Version: 2 (0x1)
Signature Algorithm: sha256WithRSAEncryption
Issuer: C=US, ST=Montana, L=Bozeman, O=Sawtooth, OU=Consulting, CN=www.wolfssl.com, emailAddress=info@wolfssl.com
Last Update: Dec 20 23:07:25 2021 GMT
Next Update: Sep 15 23:07:25 2024 GMT
CRL extensions:
X509v3 CRL Number:
2
Revoked Certificates:
Serial Number: 2 (0x2)
Revocation Date: Dec 20 23:07:25 2021 GMT
Signature Algorithm: sha256WithRSAEncryption
8b:c0:b8:cb:03:5c:8c:d1:53:b2:c5:b1:4d:f3:b3:e8:13:bf:
5f:a7:1a:cc:74:e8:06:66:c1:cb:89:c3:e3:b3:fb:68:4e:8f:
d0:5b:33:d8:ed:5e:14:b3:21:c8:c0:06:66:97:6d:69:96:78:
bd:a9:d1:59:85:0f:13:29:2d:2f:49:87:94:84:14:94:38:74: …
```
> Adding -text arg for crl command

- src/dh/clu_dh.c
ZD15621
To reproduce failure do:
First build FIPS version of wolfSSL
```
cd wolfssl
./fips-check linuxv2 keep
cd XXX-fips-test
./configure --enable-fips=v2 --enable-wolfclu CPPFLAGS="-DHAVE_FFDHE_4096 -DWOLFSSL_PUBLIC_MP"
make
./fips-hash.sh
make
sudo make install
```
Then build wolfCLU
```
cd wolfclu
./configure
make
./wolfssl dhparam 4096 -out out.pem -check 4096
```
Before this change there would be an error of DHparams not supported due to WOLFSSH_DH_EXTRA not being defined with the version of FIPS. (check wolfssl/wolfcrypt/settings.h to see WOLFSSH_DH_EXTRA getting undefined).
> add copy of dh to der and params functions for older FIPS builds

- configure.ac
- src/dh/clu_dh.c
DH issue is with FIPSv2 SP build, there is a clear on the mp_int before it has been initialized.
> Fix FIPS DH issue and cross compile warning

- configure.ac
https://github.com/wolfSSL/wolfCLU/commit/8130d3a1a6e1edb58abf737923ca59cdeb032b6c broke all testing with master.
ACTION: Gave wolfCLU it's own CLU-PRB-manager and a test that ensures changes with wolfCLU do not negatively impact PRB testing against master as well!
> Fix configure error that can't locate libwolfssl when using custom install location

- src/genkey/clu_genkey.c
- src/genkey/clu_genkey_setup.c
- wolfclu/genkey/clu_genkey.h
1. Fixes bug where generating an ECC key created a zero-byte file alongside the output keys.
2. Unifies the seemingly redundant `PUB_ONLY`/`PRIV_ONLY`  and `PUB_ONLY_FILE`/`PRIV_ONLY_FILE` enums
Running the following command on a build based on the `main` branch:
```
./wolfssl genkey ecc -out mykey -outform pem -output KEYPAIR
```
generates `mykey.priv` and `mykey.pub` but also the empty file `mykey`. 
This PR should eliminate the extra `mykey` file
> removed erroneous file generation on ecc keygen

- src/pkey/clu_rsa.c
Reported in nightly tests against wolfSSL master branch
> fix typo in memory type

- src/tools/clu_funcs.c
This small PR adds a `void` function argument to `wolfCLU_help()` and `wolfCLU_encryptHelp()` to match their prototypes. This fixes a build warning/error on OSX.
Found while going through wolfSSL 5.6.6 release process.
> Add missing void arg to functions in clu_funcs.c

- .github/workflows/macos-check.yml
Change MacOS workflow to use prefix install instead of root install
> Use prefix install in MacOS workflow

- src/genkey/clu_genkey.c
- src/genkey/clu_genkey_setup.c
- src/sign-verify/clu_sign.c
- src/sign-verify/clu_sign_verify_setup.c
- src/sign-verify/clu_verify.c
- src/tools/clu_funcs.c
- tests/genkey_sign_ver/genkey-sign-ver-test.sh
- wolfclu/sign-verify/clu_sign.h
- wolfclu/sign-verify/clu_verify.h
- wolfclu/x509/clu_cert.h
Sign and Verify Support with PEM and DER keys ED25519, RSA, and ECC. 
RAW support for ED25519. 
wolfSSL config
```
./configure --enable-wolfclu --enable-keygen --enable-all --enable-debug
```
wolfCLU 
``` 
./configure --enable-all --enable-debug 
make
make check 
./tests/genkey_sign_ver/genkey-sign-ver-test.sh
```
> Sign and Verify Support with PEM format key ED25519, RSA, and ECC

- .github/workflows/ubuntu-check.yml
- src/clu_main.c
- src/genkey/clu_genkey.c
- src/genkey/clu_genkey_setup.c
- src/sign-verify/clu_sign.c
- src/sign-verify/clu_sign_verify_setup.c
- src/sign-verify/clu_verify.c
- tests/genkey_sign_ver/genkey-sign-ver-test.sh
- wolfclu/clu_optargs.h
- wolfclu/genkey/clu_genkey.h
- wolfclu/sign-verify/clu_sign.h
- wolfclu/sign-verify/clu_verify.h
Some fixes on:
Add Dilithium to genkey, sign-verify and gen-sig-ver test #150
> Dilithium: fix minor errors

- .github/workflows/fsanitize-check.yml
- src/genkey/clu_genkey.c
- src/genkey/clu_genkey_setup.c
- src/pkcs/clu_pkcs7.c
- src/tools/clu_funcs.c
Depends on https://github.com/wolfSSL/wolfssl/pull/8155
> add testing for ML-DSA and minor help menu fixes

- src/x509/clu_request_setup.c
- tests/x509/x509-req-test.sh
Depends on https://github.com/wolfSSL/wolfssl/pull/8136
```
$ cd wolfssl
$ ./configure --enable-wolfclu
$ make all check
$ sudo make install
$cd ../wolfCLU
$ ./configure (all tried with CFLAG=-DNO_WOLFSSL_REQ_PRINT) 
$ make all
$ ./wolfssl -genkey rsa -size 2048 -out temp.key -outform pem  -output KEYPAIR
$ ./wolfssl req -new -days 1095 -config csr.conf -key temp.key.priv -out service.csr  -outform PEM -sha256
$ openssl req -in service.csr -text
Version: 1 (0x0)
$ ./wolfssl req -in service.csr  -noout -text
Version: 1 (0x0)
```
> Fix for setting wrong version in CSRs.

- src/sign-verify/clu_x509_verify.c
> Support longer certificate chains.

- src/tools/clu_funcs.c
- tests/x509/x509-ca-test.sh
Fixes wolfCLU to use the API OBJ_sn2nid correctly after the change in wolfSSL here (https://github.com/wolfSSL/wolfssl/pull/8324)
> fix for change to OBJ sn2nid behavior in wolfSSL

- src/client/client.c
- src/server/server.c
- tests/x509/x509-req-test.sh
Fix server and client build error when build wolfSSL with --enable-kyber or --enable-mldsa.
> fix client and server KEM macro

- src/genkey/clu_genkey.c
- src/genkey/clu_genkey_setup.c
Some arrays have strings used to initialize them with explicit null terminators as padding. This padding method causes gcc to throw warnings so I removed it. Conforming C compilers should automatically fill the rest of the array slots with null terminators.
my compiler info:
gcc version 15.1.1 20250425 (Red Hat 15.1.1-1) (GCC)
> Fixed problems with string init of array

- tests/x509/x509-req-test.sh
This PR improves the `x509-req-test.sh` not to keep wrong error status unintentionally, after an error happens.
The script will add configurations to `test-prompt.conf` and `test.conf` while running.
Once the script stopped in the middle, those files are un-removed, and wrong configuration file which has duplicated contents will be generated at next run.
This PR changes from "add" to "create" for the configuration files.
wolfSSL v5.8.2:
./configure --enable-wolfclu && make install
wolfCLU:
./configure && make check
> Improve x509-req-test.sh
